### ISSUE TITLE
Build instructions for macOS?

### ISSUE THREAD

**Issue by rljacobson** [EpimetheusMusicPlayer/Epimetheus#1]
I see the XCode project, but it assumes the existence of 
`Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xconfig`
and
`ephemeral/Flutter-Generated.xcconfig`.
I assume these are Flutter-specific. What's the build process on macOS?

**Comment by hacker1024** [comment]
With the Flutter SDK installed: `flutter run -d macos`.
Please note that I've been privately rewriting the app for over a year now, as I'm not happy with this version's architecture. This version is abandoned.
